export const UPSERT_SELECTED_NOTE = 'UPSERT_SELECTED_NOTE';
export const DELETE_SELECTED_NOTE = 'DELETE_SELECTED_NOTE';
export const EDIT_SELECTED_NOTE = 'EDIT_SELECTED_NOTE';
export const REMOVE_SELECTED_NOTE = 'REMOVE_SELECTED_NOTE';